### ISSUE TITLE
Le test de endpoint de fichier renvoie 404 lorsqu'il contient {{xxx}}

### ISSUE THREAD

**Issue by thomaslhostis** [voyages-sncf-technologies/hesperides-data-migration#69]

**Comment by Lucas-C** [comment]
@thomaslhostis De mémoire tu avais corrigé ça non ?

**Comment by thomaslhostis** [comment]
C'est une bonne question. Je ne trouve pas le test. J'ajoute le tag.

**Comment by thomaslhostis** [comment]
Au temps pour moi, j'étais dans Hespérides. Oui c'est corrigé.
